### ISSUE TITLE
user settable maximum frequency

### ISSUE THREAD

**Issue by ndvbd** [swharden/Python-GUI-examples#2]
How we can change the maximum frequency shown?

**Comment by swharden** [comment]
If you're referring to the [audio monitor](https://github.com/swharden/Python-GUI-examples/tree/master/2016-07-37_qt_audio_monitor) the maximum frequency is half of the sample rate. If no sample rate is given, I think it uses the sound card's lowest possible rate. To assign a higher rate, change [go.py line 17](https://github.com/swharden/Python-GUI-examples/blob/master/2016-07-37_qt_audio_monitor/go.py#L17) from

 `self.ear = SWHear.SWHear()`

 to 

`self.ear = SWHear.SWHear(rate=44100)`

**Comment by ndvbd** [comment]
Thanks. I'm trying to read from my Sound Blaster (Sampling rate of 96000), 
So I change it to this line, and it doesn't work.. Know why?

**Comment by swharden** [comment]
your sound card probably doesn't support 96000. Try 9600.

**Comment by swharden** [comment]
actually, try 44100. That's most commonly supported.

**Comment by ndvbd** [comment]
It does support 96000. When I use Audacity it works fine, and in python with Pyaudio it works fine as well at 96000, 24 bit.... Strange... ( I need the 96000 because I measure some 40khz signal)

**Comment by swharden** [comment]
I've gotten emails from people who have gotten this to work. I'd like to modify the code to make it easier for the end-user to set this. Can someone who got this to work let me know how they did it? Thanks

**Comment by swharden** [comment]
I fixed this issue. It turns out it had a flexible maximum frequency (of half the sample rate) all along! The reason it wasn't showing up is because I had set the graph to only plot the first 500 data points (where most of the interesting audio is for voice and music). Removing that restriction made the maximum frequency automatic, and a function of sample rate.

To control this, edit the sample rate in go.py
https://github.com/swharden/Python-GUI-examples/blob/master/2016-07-37_qt_audio_monitor/go.py#L18
