### ISSUE TITLE
ImportError: No module named 'matplotlibwidget'

### ISSUE THREAD

**Issue by titusjan** [swharden/Python-GUI-examples#7]
When running the [Matplotlib examples](https://github.com/swharden/Python-GUI-examples/tree/master/2016-07-30_qt_matplotlib_sine_scroll) I got the following error:

`ImportError: No module named 'matplotlibwidget'`

The problem is that the `MatplotlibWidget` class is not included with MatPlotLib but is part of WinPython. This means that most users cannot run your examples. See for instance [this question](https://stackoverflow.com/questions/48235729/how-can-you-display-matplotlib-objects-in-a-gui-using-qtdesigner/48250777#48250777) on Stack Overflow.

I've found the code of the `MatplotlibWidget` class [here](https://sourceforge.net/p/winpython/pyqtdesignerplugins/ci/default/tree/matplotlibwidget.py#l9). Please make it clear to readers that they need to download it, or somehow include it in your repository.

**Comment by swharden** [comment]
Thanks for noting this titusjan! I added it in the same folder as the source code and made a note in the readme. 018cac93957deff56a50e20c80ff943a1e14c61c

(I didn't notice this was an issue at the time because the WinPython distribution I was using when I made this example came with the matplotlibwidget)

note to self: I pulled it from https://github.com/swharden/Telem-A-Gator/blob/master/src/matplotlibwidget.py
